apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kibana.example.net
    http:
      paths:
        - path: /
          backend:
            serviceName: kibana-kibana
            servicePort: 5601
  tls:
    - hosts:
      - kibana.example.net
      secretName: example-net-tls
