apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-net-tls
  namespace: kube-system
spec:
  secretName: example-net-tls
  dnsNames:
  - "*.example.net"
  issuerRef:
    name: selfsigned-issuer
