apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elastic
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: kibana
    helm:
      valueFiles:
      - values.yaml

      # Values file as block file
      values: |
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
    repoURL: https://helm.elastic.co
    targetRevision: 7.6.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
