apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricbeat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elastic
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: metricbeat
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://helm.elastic.co
    targetRevision: 7.6.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
